/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iitj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author SCEA
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mnuLib = new javax.swing.JMenuItem();
        mnuIssue = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuMemb = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuABList = new javax.swing.JMenuItem();
        mnuIBList = new javax.swing.JMenuItem();
        mnuMList = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Library Application");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Library Management System");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu2.setText("Book");

        mnuLib.setText("Add Book");
        mnuLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLibActionPerformed(evt);
            }
        });
        jMenu2.add(mnuLib);

        mnuIssue.setText("Book Issue");
        mnuIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIssueActionPerformed(evt);
            }
        });
        jMenu2.add(mnuIssue);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Member");

        mnuMemb.setText("Member Console");
        mnuMemb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMembActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMemb);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Report");

        mnuABList.setText("Available Book List");
        mnuABList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuABListActionPerformed(evt);
            }
        });
        jMenu4.add(mnuABList);

        mnuIBList.setText("Issued Book List");
        mnuIBList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIBListActionPerformed(evt);
            }
        });
        jMenu4.add(mnuIBList);

        mnuMList.setText("Fine");
        mnuMList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMListActionPerformed(evt);
            }
        });
        jMenu4.add(mnuMList);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 937, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLibActionPerformed
        new AddBook().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuLibActionPerformed

    private void mnuIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIssueActionPerformed
        new Issue().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuIssueActionPerformed

    private void mnuMembActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMembActionPerformed
        new AddMem().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuMembActionPerformed

    private void mnuABListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuABListActionPerformed
        new AvailableB().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuABListActionPerformed

    private void mnuIBListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIBListActionPerformed
        new ABooks().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuIBListActionPerformed

    private void mnuMListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMListActionPerformed
        new Fine().setVisible(true);  dispose();
    }//GEN-LAST:event_mnuMListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem mnuABList;
    private javax.swing.JMenuItem mnuIBList;
    private javax.swing.JMenuItem mnuIssue;
    private javax.swing.JMenuItem mnuLib;
    private javax.swing.JMenuItem mnuMList;
    private javax.swing.JMenuItem mnuMemb;
    // End of variables declaration//GEN-END:variables
}
